# Generated by Django 5.0.1 on 2024-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0003_produitavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitavailable',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
