# Generated by Django 5.0.1 on 2024-01-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0004_produitavailable_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitavailable',
            name='availability',
        ),
    ]
